defaults:
  - /model@score_model: unet_mnist
  - /model@classifier_model: cnet_mnist
  - /model@control_net_model: control_unet_mnist
  - /data: mnist_learning_agents
  - _self_

soc:
  batch_size: 16
  eps: 1e-3
  eval_every: 10
  iters: 1000
  lambda_reg: 0.01
  learning_rate: 1e-4
  num_control_agents: 2
  num_diffusion_steps: 500
  path_to_classifier_checkpoint: /home/rbarbano/home/git/multi-agent-diffusion-working-repo/cnet.pt
  path_to_score_model_checkpoint: /home/rbarbano/home/git/multi-agent-diffusion-working-repo/checkpoints/latest.ckpt
  running_optimality_reg: 1
  sample_batch_size: 64
  optimality_target: 0
  train_num_steps: 25
  sample_num_steps: 500
  aggregator:
    mask_name: split
    use_overlap: true
    overlap_size: 4
  debug: true
  optimality_criterion: 
    name: classifier_ce

sde:
  name: VE
  sigma: 25.0

wandb:
  project: soc-agent-diffusion
  entity: null
  name: null
  tags: []