defaults:
  - /model@score_model: unet_mnist
  - /model@classifier_model: cnet_mnist
  - /model@control_net_model: control_unet_mnist
  - /data: mnist_learning_agents
  - _self_

soc:
  method: bptt
  batch_size: 16
  eps: 1e-3
  eval_every: 100
  inner_iters: 5
  lambda_reg: 1.0
  learning_rate: 1e-4
  num_control_agents: 2
  num_diffusion_steps: 500
  outer_iters: 300
  path_to_classifier_checkpoint: checkpoints/cnet.pt
  path_to_score_model_checkpoint: checkpoints/ve/latest.ckpt
  running_state_cost_scaling: 1.0
  sample_batch_size: 64
  sample_num_steps: 500
  optimality_target: 0
  train_num_steps: 25
  enable_optimality_loss_on_processes: true
  aggregator:
    mask_name: split
    use_overlap: false
    overlap_size: 0
  debug: true
  optimality_criterion: 
    name: classifier_ce_with_cooperation
  control_agent_save_path: weights

sde:
  name: VE

wandb:
  project: soc-agent-diffusion
  entity: null
  name: null
  tags: []