defaults:
  - /model@score_model: unet_mnist
  - /model@classifier_model: cnet_mnist
  - /model@control_net_model: control_unet_mnist
  - /data: mnist_learning_agents
  - _self_

soc:
  batch_size: 16
  eps: 1e-3
  eval_every: 100
  inner_iters: 5
  lambda_reg: 0.1
  learning_rate: 1e-4
  num_control_agents: 2
  num_diffusion_steps: 500
  outer_iters: 300
  path_to_classifier_checkpoint: /home/rbarbano/home/git/multi-agent-diffusion-working-repo/cnet.pt
  path_to_score_model_checkpoint: /home/rbarbano/home/git/multi-agent-diffusion-working-repo/checkpoints/latest.ckpt
  running_class_reg: 1.0
  sample_batch_size: 64
  sample_num_steps: 500
  target_digit: 0
  train_num_steps: 25
  aggregator:
    mask_name: split
    use_overlap: true
    overlap_size: 4


wandb:
  project: soc-agent-diffusion
  entity: null
  name: null
  tags: []