defaults:
  - /model: unet_mnist
  - /data: mnist_score
  - _self_

training:
  device: cuda
  evaluate_every: 1
  eval_batch_size: 64
  eval_num_steps: 500
  ema_decay: 0.999
  learning_rate: 1.0e-4
  num_epochs: 10
  load_checkpoint: false
  path_to_checkpoint: null
  checkpoint_every: 10
  checkpoint_dir: checkpoints
  grad_clip_norm: 1.0
  log_to_wandb: true
  wandb:
    project: soc-agent-diffusion
    entity: null
    name: null
    tags: []
  scheduler:
    name: null
    step_on: CosineAnnealingLR
    params: {}
  sde: 
    name: VE