training:
  checkpoint_dir: checkpoints
  checkpoint_every: 10
  detect_anomaly: false
  device: cuda
  ema_decay: 0.999
  eval_batch_size: 64
  eval_num_steps: 500
  evaluate_every: 10
  grad_clip_norm: null
  learning_rate: 1.0e-4
  load_checkpoint: false
  log_to_wandb: true
  num_epochs: 10
  path_to_checkpoint: null
  sigma: 25.0
  wandb:
    entity: null
    name: null
    project: your_project
    tags: []

model:
  in_channels: 1
  out_channels: 1
  model_channels: 32
  channel_mult: [1, 2, 4]
  num_res_blocks: 1
  attention_resolutions: []
  max_period: 0.005

data:
  loader: null