score_model:
  name: unet
  in_channels: 1
  out_channels: 1
  model_channels: 64
  channel_mult: [1, 4, 4]
  num_res_blocks: 2
  attention_resolutions: [16]
  max_period: 0.005

classifier_model:
  name: cnet
  img_size: [28, 28]
  num_classes: 10
  num_hidden_layers: 2

control_net_model:
  name: unet
  in_channels: 2
  out_channels: 1
  model_channels: 32
  channel_mult: [1, 2]
  num_res_blocks: 1
  attention_resolutions: []
  max_period: 0.005

soc:
  path_to_classifier_checkpoint: /home/rbarbano/home/git/multi-agent-diffusion-working-repo/cnet.pt
  path_to_score_model_checkpoint: /home/rbarbano/home/git/multi-agent-diffusion-working-repo/checkpoints/latest.ckpt
  num_diffusion_steps: 500
  batch_size: 16
  learning_rate: 1e-4
  iters: 1000
  lambda_reg: 0.1
  target_digit: 0


wandb:
  project: soc-agent-diffusion
  entity: null
  name: null
  tags: []